### ISSUE TITLE
collate roclet

### ISSUE THREAD

**Issue by jeroen** [hadley/roxygen3#4]
Please consider removing the collate roclet from the default.

**Comment by hadley** [comment]
I've made two changes to it: it now only modifies collate if you used
@include somewhere and if its actually necessary, ie that the default c
sort does not already satisfy the topological constraints.

I'm also thinking about a more flexible system for specifying which tags
you want to use.

On Tuesday, August 28, 2012, jeroenooms wrote:

> Please consider removing the collate roclet from the default.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hadley/roxygen3/issues/4.

## 

Assistant Professor
Department of Statistics / Rice University
http://had.co.nz/
